### ISSUE TITLE
codebase for Multitask Prompt Tuning Enables Parameter-Efficient Transfer Learning

### ISSUE THREAD

**Issue by NtaylorOX** [zhenwang9102/zhenwang9102.github.io#1]
Hi, 

Do you have the codebase for the following paper: https://openreview.net/forum?id=Nk2pDtuhTq

Great work and would love to have a play with it and reproduce/extend results etc.

Thanks!

**Comment by zhenwang9102** [comment]
Hi, just sent an email to you and please check it regarding our plan for the code release. Thanks for your interest in our work!

**Comment by zhenwang9102** [comment]
Hi, just sent an email to you and please check it regarding our plan for the code release. Thanks for your interest in our work!
